In [1]:
from pathlib import Path
import pickle
from bs4 import BeautifulSoup
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import plotly.express as px
from sklearn.cluster import DBSCAN
import simplekml
from smount_predictors import SeamountHelp
import xarray as xr

In [ ]:
points = SeamountHelp.readKMLbounds(Path('data/Seamounts_training_zone.kml'))
data = SeamountHelp.readAndFilterGRD(Path('data/vgg_swot.grd'), points)

In [16]:
np.unique(data['cluster'])

array([        -1,         56,         57, ..., 1149387103, 1149387104,
       1149387105])

In [ ]:
mounts = data.groupby('cluster').mean().reset_index()
kml = simplekml.Kml()
for i, row in mounts.iterrows():
    kml.newpoint(name=f'{row.cluster}', coords=[(row.lon, row.lat, row.z)])
kml.save('out/global_mounts.kml')

In [11]:
mask = xr.open_dataarray('data/depth_mask.grd')
# np.unique(mask.values)
mask.values

array([[ 1.,  1.,  1., ..., nan,  1.,  1.],
       [nan, nan, nan, ..., nan, nan, nan],
       [ 1.,  1.,  1., ..., nan,  1.,  1.],
       ...,
       [ 0.,  0.,  0., ..., nan,  0.,  0.],
       [nan, nan, nan, ..., nan, nan, nan],
       [ 0.,  0.,  0., ..., nan,  0.,  0.]], dtype=float32)

In [12]:
srtm = xr.open_dataarray('data/srtm_swotsize.grd')
srtm.values

array([[   50.5   ,    50.5   ,    51.25  , ...,        nan,    49.5   ,
           49.75  ],
       [       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       [   49.    ,    50.    ,    50.5   , ...,        nan,    49.    ,
           49.    ],
       ...,
       [-1577.6608, -1568.7339, -1564.4452, ...,        nan, -1587.4585,
        -1584.2736],
       [       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       [-1557.6478, -1552.5125, -1547.5945, ...,        nan, -1564.1993,
        -1561.5991]], dtype=float32)